### ISSUE TITLE
importlib.metadata.PackageNotFoundError: exchange_calendars in AWS lambda

### ISSUE THREAD

**Issue by zhemaituk** [gerrymanoim/exchange_calendars#213]
Reproduced after upgrade from 4.0.2 to 4.1.

Reproducible when packaging exchange-calendar inside AWS lambda function using serverless.
Traceback:
```
Traceback (most recent call last):
  File "/var/task/src/handler/httpbase.py", line 40, in __call__
    return self.response(event, context)
  File "/var/task/src/handler/httpbase.py", line 108, in response
    from src.dateutils import NonTradingDayException
  File "/var/task/src/dateutils.py", line 9, in <module>
    import pandas_market_calendars as mcal
  File "/var/task/pandas_market_calendars/__init__.py", line 19, in <module>
    from .calendar_registry import get_calendar, get_calendar_names
  File "/var/task/pandas_market_calendars/calendar_registry.py", line 28, in <module>
    from .exchange_calendars_mirror import *
  File "/var/task/pandas_market_calendars/exchange_calendars_mirror.py", line 8, in <module>
    import exchange_calendars
  File "/var/task/exchange_calendars/__init__.py", line 46, in <module>
    __version__ = version("exchange_calendars")
  File "/var/lang/lib/python3.9/importlib/metadata.py", line 569, in version
    return distribution(distribution_name).version
  File "/var/lang/lib/python3.9/importlib/metadata.py", line 542, in distribution
    return Distribution.from_name(distribution_name)
  File "/var/lang/lib/python3.9/importlib/metadata.py", line 196, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: exchange_calendars
```

Packaging is pretty standard for serverless-python-requirements plugin:
```
  pythonRequirements:
    slim: true
    dockerizePip: true
    dockerRunCmdExtraArgs: [ '--platform', 'linux/arm64/v8' ]
    dockerImage: public.ecr.aws/sam/build-python3.9:latest-arm64
```

**Comment by gerrymanoim** [comment]
Hmm @maread99  - any idea here? 

Maybe we should also make this try/catch so just in case this never fails

**Comment by maread99** [comment]
I'm not familiar with the context here, but seems that for whatever reason `importlib.metadata` was unable to resolve the version. The [importlib.metadata doc](https://docs.python.org/3/library/importlib.metadata.html) explains how the module gets the version from the metadata of the installed package, where...

> By “installed package” we generally mean a third-party package installed into Python’s site-packages directory via tools such as [pip](https://pypi.org/project/pip/). Specifically, it means a package with either a discoverable dist-info or egg-info directory

I'm guessing this isn't the case in this context.

#214 proposes a fix by falling back on the version as set in `_version.py` when the package is built.

**Comment by zhemaituk** [comment]
Thank you for the quick resolution! 4.1.1 works well.

**Comment by maread99** [comment]
Thanks for letting us know that all's working.
