### ISSUE TITLE
ecal: AttributeError: 'datetime.timezone' object has no attribute 'key'

### ISSUE THREAD

**Issue by ValueRaider** [gerrymanoim/exchange_calendars#360]
Pandas version = 2.0.3
xcal version = master latest commit 597c9f

```
$ ./etc/ecal XASX 2010
Traceback (most recent call last):
  File "exchange_calendars/./etc/ecal", line 160, in <module>
    main(sys.argv)
  File "exchange_calendars/./etc/ecal", line 143, in main
    month_strings = [
                    ^
  File "exchange_calendars/./etc/ecal", line 144, in <listcomp>
    [
  File "exchange_calendars/./etc/ecal", line 145, in <listcomp>
    _render_month(
  File "exchange_calendars/./etc/ecal", line 58, in _render_month
    if calendar.is_session(d):
       ^^^^^^^^^^^^^^^^^^^^^^
  File "exchange_calendars/exchange_calendars/exchange_calendar.py", line 1251, in is_session
    date = parse_date(date, "date", self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "exchange_calendars/exchange_calendars/calendar_helpers.py", line 379, in parse_date
    f"Parameter `{param_name}` received with timezone defined as '{ts.tz.key}'"
                                                                   ^^^^^^^^^
AttributeError: 'datetime.timezone' object has no attribute 'key'
```

**Comment by maread99** [comment]
Thanks @ValueRaider. I couldn't replicate the error although suspect that I can see what's happening. Hopefully #361 should fix it.
